### ISSUE TITLE
Helper Method For Acquiring NodeId

### ISSUE THREAD

**Issue by mattc41190** [webdriverio/wdio-devtools-service#1]
I have been playing with this plugin and it seems like nodeId is used very regularly. The method for acquiring the nodeId is very easy, but probably still deserving of a helper so people aren't writing boiler plate everywhere. The method for acquiring the nodeId is a little bit opaque if you have never used it before.

Domains where NodeId is used:

* Accessibility -- HEAVY
* CSS -- HEAVY
* DOM -- HEAVY
* DOMDebugger
* Profiler

The helper would likely look like:

```javascript
get nodeId(selector) {
        let _document = browser.cdp('DOM', 'getDocument');
        return browser.cdp('DOM', 'querySelector', {nodeId: _document.root.nodeId, selector});
}
```

**Comment by christian-bromann** [comment]
PRs welcome 😉

**Comment by christian-bromann** [comment]
Implemented in https://github.com/webdriverio/webdriverio/pull/2918
