### ISSUE TITLE
Chromeheadless support

### ISSUE THREAD

**Issue by dhirajbodicherla** [webdriverio/wdio-devtools-service#3]
The code seems to be checking for chrome and version. https://github.com/webdriverio/wdio-devtools-service/blob/master/lib/devtools.js#L6

Is this intentional? Or can this service work with chromeheadless as well but not supported yet?

**Comment by christian-bromann** [comment]
Not sure what the version check has to do with whether or not Chrome runs in headless mode. It checks the version because only Chrome 63 and up has Multi client functionality. Chrome headless should work with this service.

**Comment by mielientiev** [comment]
@christian-bromann hey, for me, wdio-devtools-service is not working in headless mode. Do you have any examples of running it in chrome headless with wdio?
