### ISSUE TITLE
Can I Set Request Header Host

### ISSUE THREAD

**Issue by psmod2** [webdriverio/wdio-devtools-service#6]
Hi,

So as I have access to Chrome Dev Tools - does this mean I can set the request header host e.g. I can't see how this is done?

I'm under the impression that this tool is more for listening to events rather than setting?

Any help appreicated

**Comment by christian-bromann** [comment]
@psmod2 you can set headers for any request being made by the browser using [setRequestInterception](https://chromedevtools.github.io/devtools-protocol/tot/Network#method-setRequestInterception). Then you need to listen on the [requestIntercepted](https://chromedevtools.github.io/devtools-protocol/tot/Network#event-requestIntercepted) event to call [continueInterceptedRequest](https://chromedevtools.github.io/devtools-protocol/tot/Network#method-continueInterceptedRequest) with modified headers.

**Comment by psmod2** [comment]
@christian-bromann 
Thanks - however I'm trying that with no luck.

I simply want to append my custom request header to any network call:

I'm trying:

```
browser.cdp('Network', 'enable')

browser.cdp('Network', 'setRequestInterception', {
      patterns: [{ urlPattern: '*' }]
})

browser.on('Network.requestIntercepted', (params) => {
      console.log(params.request.headers)

      browser.cdp('Network', 'continueInterceptedRequest', {
        request:
          {
            headers:
              {
                'myCustomHeader': 'aValue'
              }
          }
      })

})
```

**Comment by christian-bromann** [comment]
Please see the docs, it probably has to be like this:
```js
browser.cdp('Network', 'enable')

browser.cdp('Network', 'setRequestInterception', {
    patterns: [{ urlPattern: '*' }]
})

browser.on('Network.requestIntercepted', (params) => {
    console.log(params.request.headers)
    browser.cdp('Network', 'continueInterceptedRequest', {
        interceptionId: params.interceptionId
        headers: { 'myCustomHeader': 'aValue' }
    })
})
```

**Comment by psmod2** [comment]
Hi,

Thanks - so that actually applies my customer header value - by doing a browser.refresh() i see it applied. However it gets stuck in the continueInterceptedRequest section - i.e. it just pauses there. Is there to break out of it?

**Comment by 415DomSmith** [comment]
I also need to use the pattern @christian-bromann mentions, but run in to the same issue as @psmod2

**Comment by pmerwin** [comment]
Christian's example worked for me , but I had to add a comma here:

interceptionId: params.interceptionId , <<<
        headers: { 'myCustomHeader': 'aValue' }

**Comment by christian-bromann** [comment]
@psmod2 interesting .. yeah that kind of stuff is not fully documented in the devtools protocol
